### PR TITLE
Set namespace not in the scope of interaction for Prometheus Operator created for collection

### PR DESCRIPTION
**Pull request by kkujawa-sumo**
There is additional Prometheus Operator on OpenShift which runs with following arguments:
```
Containers:
  prometheus-operator:
    Container ID:  cri-o://2a0849d9178bfbb9a83d3084e6f4ab727680db9bade1a1ec16437c00fbe1a7c2
    Image:         quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4e580c9df1a09ab8e0647fc0e378d792a4c3078b4a06120264ab00917e71e783
    Image ID:      quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4e580c9df1a09ab8e0647fc0e378d792a4c3078b4a06120264ab00917e71e783
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      --kubelet-service=kube-system/kubelet
      --logtostderr=true
      --config-reloader-image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:683fdffdd9f89c136f34d8679e73e3c22cc8cd56694fed1a98d7e423a98cb9cb
      --prometheus-config-reloader=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0dcee8f61a4278efc65669c1424dd1b137299d235b1e33cf0cd1df7768df6e53
      --namespaces=openshift-apiserver,openshift-apiserver-operator,openshift-authentication,openshift-authentication-operator,openshift-cloud-credential-operator,openshift-cluster-machine-approver,openshift-cluster-samples-operator,openshift-cluster-storage-operator,openshift-cluster-version,openshift-config-operator,openshift-console-operator,openshift-controller-manager,openshift-controller-manager-operator,openshift-dns,openshift-dns-operator,openshift-etcd-operator,openshift-image-registry,openshift-ingress,openshift-ingress-operator,openshift-insights,openshift-kube-apiserver,openshift-kube-apiserver-operator,openshift-kube-controller-manager,openshift-kube-controller-manager-operator,openshift-kube-scheduler,openshift-kube-scheduler-operator,openshift-kube-storage-version-migrator,openshift-kube-storage-version-migrator-operator,openshift-machine-api,openshift-machine-config-operator,openshift-marketplace,openshift-monitoring,openshift-multus,openshift-oauth-apiserver,openshift-operator-lifecycle-manager,openshift-sdn,openshift-service-ca-operator,openshift-user-workload-monitoring
      --prometheus-instance-namespaces=openshift-monitoring
      --thanos-ruler-instance-namespaces=openshift-monitoring
      --alertmanager-instance-namespaces=openshift-monitoring
      --config-reloader-cpu=0
      --config-reloader-memory=0
      --web.enable-tls=true
      --web.tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
      --web.tls-min-version=VersionTLS12
```

Argument `namespaces` indicates namespaces in the scope of interaction for Prometheus operator, see [this](https://github.com/prometheus-operator/prometheus-operator/blob/d88f7f0fc12b81aaa6e94e5a37a29fde7379d68e/cmd/operator/main.go#L191).
Argument `deny-namespaces` allows to set namespace not in the scope of interaction for Prometheus operator, see [this](https://github.com/prometheus-operator/prometheus-operator/blob/d88f7f0fc12b81aaa6e94e5a37a29fde7379d68e/cmd/operator/main.go#L192).

Logs from Prometheus Operator created for Sumo Logic collection without `deny-namespaces` set:
```
kubectl logs -n sumologic-system test-openshift-kube-promet-operator-cf9dbd4b-2cxvk --tail 10 | grep openshift-monitoring
level=info ts=2021-05-12T18:45:47.82380121Z caller=operator.go:663 component=alertmanageroperator msg="sync alertmanager" key=openshift-monitoring/main
level=info ts=2021-05-12T18:45:47.909380148Z caller=operator.go:663 component=alertmanageroperator msg="sync alertmanager" key=openshift-monitoring/main
level=info ts=2021-05-12T18:45:47.97987556Z caller=operator.go:1145 component=prometheusoperator msg="sync prometheus" key=openshift-monitoring/k8s
level=info ts=2021-05-12T18:45:47.985343408Z caller=operator.go:663 component=alertmanageroperator msg="sync alertmanager" key=openshift-monitoring/main
level=info ts=2021-05-12T18:45:48.072642821Z caller=operator.go:663 component=alertmanageroperator msg="sync alertmanager" key=openshift-monitoring/main
level=info ts=2021-05-12T18:45:48.140112835Z caller=operator.go:663 component=alertmanageroperator msg="sync alertmanager" key=openshift-monitoring/main
level=info ts=2021-05-12T18:45:48.203740884Z caller=operator.go:663 component=alertmanageroperator msg="sync alertmanager" key=openshift-monitoring/main
level=info ts=2021-05-12T18:45:48.262704672Z caller=operator.go:663 component=alertmanageroperator msg="sync alertmanager" key=openshift-monitoring/main
level=info ts=2021-05-12T18:45:48.34811938Z caller=operator.go:1145 component=prometheusoperator msg="sync prometheus" key=openshift-monitoring/k8s
```

Logs from Prometheus Operator created for Sumo Logic collection with `deny-namespaces` set :
```
kubectl logs -n sumologic-system test-openshift-kube-promet-operator-5cbd79999b-xv5qd
level=info ts=2021-05-12T18:58:40.927960881Z caller=main.go:228 msg="Starting Prometheus Operator" version="(version=0.43.2, branch=refs/tags/v0.43.2, revision=b86ab77239f2a11ee69ad05b24122958d8b2df5b)"
level=info ts=2021-05-12T18:58:40.928012662Z caller=main.go:229 build_context="(go=go1.14.10, user=simonpasquier, date=20201109-10:55:44)"
ts=2021-05-12T18:58:40.943586334Z caller=main.go:106 msg="Starting insecure server on [::]:8080"
level=info ts=2021-05-12T18:58:40.954492263Z caller=operator.go:419 component=prometheusoperator msg="connection established" cluster-version=v1.19.0+9f84db3
level=info ts=2021-05-12T18:58:40.954516477Z caller=operator.go:300 component=thanosoperator msg="connection established" cluster-version=v1.19.0+9f84db3
level=info ts=2021-05-12T18:58:40.95454368Z caller=operator.go:428 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2021-05-12T18:58:40.954553306Z caller=operator.go:309 component=thanosoperator msg="CRD API endpoints ready"
level=info ts=2021-05-12T18:58:40.954648598Z caller=operator.go:434 component=alertmanageroperator msg="connection established" cluster-version=v1.19.0+9f84db3
level=info ts=2021-05-12T18:58:40.954673868Z caller=operator.go:443 component=alertmanageroperator msg="CRD API endpoints ready"
I0512 18:58:40.954619       1 shared_informer.go:240] Waiting for caches to sync for thanos
I0512 18:58:40.954624       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:40.954710       1 shared_informer.go:240] Waiting for caches to sync for alertmanager
I0512 18:58:41.072073       1 shared_informer.go:247] Caches are synced for thanos 
I0512 18:58:41.072125       1 shared_informer.go:240] Waiting for caches to sync for thanos
I0512 18:58:41.072132       1 shared_informer.go:247] Caches are synced for thanos 
I0512 18:58:41.077982       1 shared_informer.go:247] Caches are synced for alertmanager 
I0512 18:58:41.078027       1 shared_informer.go:240] Waiting for caches to sync for alertmanager
I0512 18:58:41.078035       1 shared_informer.go:247] Caches are synced for alertmanager 
I0512 18:58:41.078078       1 shared_informer.go:240] Waiting for caches to sync for thanos
I0512 18:58:41.101062       1 shared_informer.go:240] Waiting for caches to sync for alertmanager
I0512 18:58:41.169356       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.169495       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.169508       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.169546       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.169554       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.169587       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.169595       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.169617       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.169625       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.169653       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.169661       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.169682       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.186194       1 shared_informer.go:247] Caches are synced for thanos 
I0512 18:58:41.186265       1 shared_informer.go:240] Waiting for caches to sync for thanos
I0512 18:58:41.186279       1 shared_informer.go:247] Caches are synced for thanos 
I0512 18:58:41.186308       1 shared_informer.go:240] Waiting for caches to sync for thanos
I0512 18:58:41.186316       1 shared_informer.go:247] Caches are synced for thanos 
I0512 18:58:41.186339       1 shared_informer.go:240] Waiting for caches to sync for thanos
I0512 18:58:41.186347       1 shared_informer.go:247] Caches are synced for thanos 
level=info ts=2021-05-12T18:58:41.186365666Z caller=operator.go:261 component=thanosoperator msg="successfully synced all caches"
I0512 18:58:41.470773       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.470833       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.470841       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.470859       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.470864       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.470877       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.470882       1 shared_informer.go:247] Caches are synced for prometheus 
level=info ts=2021-05-12T18:58:41.470896221Z caller=operator.go:358 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2021-05-12T18:58:41.471181642Z caller=operator.go:1145 component=prometheusoperator msg="sync prometheus" key=sumologic-system/test-openshift-kube-promet-prometheus
I0512 18:58:41.501278       1 shared_informer.go:247] Caches are synced for alertmanager 
I0512 18:58:41.501327       1 shared_informer.go:240] Waiting for caches to sync for alertmanager
I0512 18:58:41.501335       1 shared_informer.go:247] Caches are synced for alertmanager 
I0512 18:58:41.501351       1 shared_informer.go:240] Waiting for caches to sync for alertmanager
I0512 18:58:41.501356       1 shared_informer.go:247] Caches are synced for alertmanager 
I0512 18:58:41.501369       1 shared_informer.go:240] Waiting for caches to sync for alertmanager
I0512 18:58:41.501373       1 shared_informer.go:247] Caches are synced for alertmanager 
level=info ts=2021-05-12T18:58:41.501386571Z caller=operator.go:275 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2021-05-12T18:58:42.166299741Z caller=operator.go:1145 component=prometheusoperator msg="sync prometheus" key=sumologic-system/test-openshift-kube-promet-prometheus
level=info ts=2021-05-12T18:58:42.581362937Z caller=operator.go:1145 component=prometheusoperator msg="sync prometheus" key=sumologic-system/test-openshift-kube-promet-prometheus
level=info ts=2021-05-12T18:58:55.328918245Z caller=operator.go:1145 component=prometheusoperator msg="sync prometheus" key=sumologic-system/test-openshift-kube-promet-prometheus
vagrant@sumologic-kubernetes-collection-operator:/operator$ kubectl logs -n sumologic-system test-openshift-kube-promet-operator-5cbd79999b-xv5qd | grep openshift-monitoring
vagrant@sumologic-kubernetes-collection-operator:/operator$ kubectl logs -n sumologic-system test-openshift-kube-promet-operator-5cbd79999b-xv5qd 
level=info ts=2021-05-12T18:58:40.927960881Z caller=main.go:228 msg="Starting Prometheus Operator" version="(version=0.43.2, branch=refs/tags/v0.43.2, revision=b86ab77239f2a11ee69ad05b24122958d8b2df5b)"
level=info ts=2021-05-12T18:58:40.928012662Z caller=main.go:229 build_context="(go=go1.14.10, user=simonpasquier, date=20201109-10:55:44)"
ts=2021-05-12T18:58:40.943586334Z caller=main.go:106 msg="Starting insecure server on [::]:8080"
level=info ts=2021-05-12T18:58:40.954492263Z caller=operator.go:419 component=prometheusoperator msg="connection established" cluster-version=v1.19.0+9f84db3
level=info ts=2021-05-12T18:58:40.954516477Z caller=operator.go:300 component=thanosoperator msg="connection established" cluster-version=v1.19.0+9f84db3
level=info ts=2021-05-12T18:58:40.95454368Z caller=operator.go:428 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2021-05-12T18:58:40.954553306Z caller=operator.go:309 component=thanosoperator msg="CRD API endpoints ready"
level=info ts=2021-05-12T18:58:40.954648598Z caller=operator.go:434 component=alertmanageroperator msg="connection established" cluster-version=v1.19.0+9f84db3
level=info ts=2021-05-12T18:58:40.954673868Z caller=operator.go:443 component=alertmanageroperator msg="CRD API endpoints ready"
I0512 18:58:40.954619       1 shared_informer.go:240] Waiting for caches to sync for thanos
I0512 18:58:40.954624       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:40.954710       1 shared_informer.go:240] Waiting for caches to sync for alertmanager
I0512 18:58:41.072073       1 shared_informer.go:247] Caches are synced for thanos 
I0512 18:58:41.072125       1 shared_informer.go:240] Waiting for caches to sync for thanos
I0512 18:58:41.072132       1 shared_informer.go:247] Caches are synced for thanos 
I0512 18:58:41.077982       1 shared_informer.go:247] Caches are synced for alertmanager 
I0512 18:58:41.078027       1 shared_informer.go:240] Waiting for caches to sync for alertmanager
I0512 18:58:41.078035       1 shared_informer.go:247] Caches are synced for alertmanager 
I0512 18:58:41.078078       1 shared_informer.go:240] Waiting for caches to sync for thanos
I0512 18:58:41.101062       1 shared_informer.go:240] Waiting for caches to sync for alertmanager
I0512 18:58:41.169356       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.169495       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.169508       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.169546       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.169554       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.169587       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.169595       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.169617       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.169625       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.169653       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.169661       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.169682       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.186194       1 shared_informer.go:247] Caches are synced for thanos 
I0512 18:58:41.186265       1 shared_informer.go:240] Waiting for caches to sync for thanos
I0512 18:58:41.186279       1 shared_informer.go:247] Caches are synced for thanos 
I0512 18:58:41.186308       1 shared_informer.go:240] Waiting for caches to sync for thanos
I0512 18:58:41.186316       1 shared_informer.go:247] Caches are synced for thanos 
I0512 18:58:41.186339       1 shared_informer.go:240] Waiting for caches to sync for thanos
I0512 18:58:41.186347       1 shared_informer.go:247] Caches are synced for thanos 
level=info ts=2021-05-12T18:58:41.186365666Z caller=operator.go:261 component=thanosoperator msg="successfully synced all caches"
I0512 18:58:41.470773       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.470833       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.470841       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.470859       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.470864       1 shared_informer.go:247] Caches are synced for prometheus 
I0512 18:58:41.470877       1 shared_informer.go:240] Waiting for caches to sync for prometheus
I0512 18:58:41.470882       1 shared_informer.go:247] Caches are synced for prometheus 
level=info ts=2021-05-12T18:58:41.470896221Z caller=operator.go:358 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2021-05-12T18:58:41.471181642Z caller=operator.go:1145 component=prometheusoperator msg="sync prometheus" key=sumologic-system/test-openshift-kube-promet-prometheus
I0512 18:58:41.501278       1 shared_informer.go:247] Caches are synced for alertmanager 
I0512 18:58:41.501327       1 shared_informer.go:240] Waiting for caches to sync for alertmanager
I0512 18:58:41.501335       1 shared_informer.go:247] Caches are synced for alertmanager 
I0512 18:58:41.501351       1 shared_informer.go:240] Waiting for caches to sync for alertmanager
I0512 18:58:41.501356       1 shared_informer.go:247] Caches are synced for alertmanager 
I0512 18:58:41.501369       1 shared_informer.go:240] Waiting for caches to sync for alertmanager
I0512 18:58:41.501373       1 shared_informer.go:247] Caches are synced for alertmanager 
level=info ts=2021-05-12T18:58:41.501386571Z caller=operator.go:275 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2021-05-12T18:58:42.166299741Z caller=operator.go:1145 component=prometheusoperator msg="sync prometheus" key=sumologic-system/test-openshift-kube-promet-prometheus
level=info ts=2021-05-12T18:58:42.581362937Z caller=operator.go:1145 component=prometheusoperator msg="sync prometheus" key=sumologic-system/test-openshift-kube-promet-prometheus
level=info ts=2021-05-12T18:58:55.328918245Z caller=operator.go:1145 component=prometheusoperator msg="sync prometheus" key=sumologic-system/test-openshift-kube-promet-prometheus
```

I'll prepare proper pull request with documentation to https://github.com/SumoLogic/sumologic-kubernetes-collection

### CODE REVIEW

**Review by sumo-drosiek — APPROVED** [review]
:taco:

**Comment by pmalek-sumo** [comment]
There's a lot of information in the description which is nice but I feel like there's still a small piece missing saying why exactly do we need this change?

What does this PR address/fix/improve?

**Comment by sumo-drosiek** [comment]
@pmalek-sumo It prevents our prometheus operator to watch namespaces which OS operator takes care about

**Comment by pmalek-sumo** [comment]
> @pmalek-sumo It prevents our prometheus operator to watch namespaces which OS operator takes care about, so we don't try to manage objects already managed by them

Why there's considerably more logs when "deny-namespaces set :"? Shouldn't then be less logs? From less resources from less namespaces?

**Comment by kkujawa-sumo** [comment]
> > @pmalek-sumo It prevents our prometheus operator to watch namespaces which OS operator takes care about, so we don't try to manage objects already managed by them
> 
> Why there's considerably more logs when "deny-namespaces set :"? Shouldn't then be less logs? From less resources from less namespaces?

There is less logs ;) because Prometheus Operator does not watch for namespaces specified as `deny-namespaces`.  Commands used for showing logs are different because with `deny-namespaces` output for this commands is empty 
`kubectl logs -n sumologic-system test-openshift-kube-promet-operator-cf9dbd4b-2cxvk --tail 10 | grep openshift-monitoring`. I've thought that showing the full log for the configuration with `deny-namespaces` is better than showing empty output, but maybe I was wrong...

**Comment by pmalek-sumo** [comment]
Ok got it, thanks.

**Pull request merged**
